version: 2

models:
  - name: rpt_pelne_dokumenty
    description: "Tabela dokumentow (naglowki i pozycje)"
    columns:
      - name: kom
        description: "komentarz do dokumentu"
      - name: opis
        description: "opis pozycji dokmentu"
        tests:
          - not_null
  #       - relationships:
  #           to: ref('model.sql')
  #           field: xxx
      
# Sekcja dla tabel, które już są w BigQuery (brak modeli SQL w dbt)
sources:
  - name: bq_tables   # Dowolna nazwa dla grupy źródeł
    database: crafty-chiller-504711-m7 
    schema: test_data_set          
    tables:
      - name: dok
        columns:
          - name: dok_id
            description: "Klucz główny"
            tests:
              - unique
              - not_null
      - name: p_dok
        columns:
          - name: p_dok_lp
            tests:
            - accepted_values:
                arguments:
                  values: [1,2,3,4,5]      

